
const NECESSARY_PARAM_IS_NULL = '有必传的参数为空'
const UNIQUE_FIELD_DUPLICATE = '有UNIQUE字段重复'
const ADMIN_NOT_EXIST = '该手机号的admin不存在'
const ADMIN_PASSWORD_WRONG = 'admin密码错误'
const UNAUTHORIZED = '未授权'

module.exports = {
  NECESSARY_PARAM_IS_NULL,
  UNIQUE_FIELD_DUPLICATE,
  ADMIN_NOT_EXIST,
  ADMIN_PASSWORD_WRONG,
  UNAUTHORIZED
}